export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
  },
  PRODUCTS: {
    LIST: '/products',
    DETAIL: (id: number) => `/products/${id}`,
    CREATE: '/products',
    UPDATE: (id: number) => `/products/${id}`,
    DELETE: (id: number) => `/products/${id}`,
    SEARCH: '/products/search',
    FEATURED: '/products/featured',
    BY_CATEGORY: (categoryId: number) => `/products/category/${categoryId}`,
    BY_SHOP: (shopId: number) => `/products/shop/${shopId}`,
  },
  CATEGORIES: {
    LIST: '/categories',
    DETAIL: (id: number) => `/categories/${id}`,
    CREATE: '/categories',
    UPDATE: (id: number) => `/categories/${id}`,
    DELETE: (id: number) => `/categories/${id}`,
    TREE: '/categories/tree',
  },
  CART: {
    GET: '/cart',
    ADD_ITEM: '/cart/items',
    UPDATE_ITEM: (itemId: number) => `/cart/items/${itemId}`,
    REMOVE_ITEM: (itemId: number) => `/cart/items/${itemId}`,
    CLEAR: '/cart/clear',
  },
  ORDERS: {
    LIST: '/orders',
    DETAIL: (id: number) => `/orders/${id}`,
    CREATE: '/orders',
    UPDATE_STATUS: (id: number) => `/orders/${id}/status`,
    UPDATE_PAYMENT: (id: number) => `/orders/${id}/payment`,
    CANCEL: (id: number) => `/orders/${id}/cancel`,
    MY_ORDERS: '/orders/my-orders',
  },
  USERS: {
    LIST: '/users',
    DETAIL: (id: number) => `/users/${id}`,
    UPDATE: (id: number) => `/users/${id}`,
    DELETE: (id: number) => `/users/${id}`,
    PROFILE: '/users/profile',
    UPDATE_PASSWORD: '/users/password',
  },
  SHOPS: {
    LIST: '/shops',
    DETAIL: (id: number) => `/shops/${id}`,
    CREATE: '/shops',
    UPDATE: (id: number) => `/shops/${id}`,
  },
  WISHLIST: {
    GET: '/wishlist',
    ADD: '/wishlist/items',
    REMOVE: (itemId: number) => `/wishlist/items/${itemId}`,
    CLEAR: '/wishlist/clear',
  },
  ADMIN: {
    DASHBOARD_STATS: '/admin/dashboard/stats',
    SALES_REPORT: '/admin/reports/sales',
    INVENTORY_REPORT: '/admin/reports/inventory',
  },
} as const;
